apiVersion: v1
data:
  password: azhzcGFzc3dvcmQK
kind: Secret
metadata:
  name: mysql-pass
  namespace: planespotter
type: Opaque

---

apiVersion: v1
data:
  password: bXl1c2VycGFzc3dvcmQK
kind: Secret
metadata:
  name: mysqluser-pass
  namespace: planespotter
type: Opaque
