# Headless service used by WordPress
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  ports:
    - port: 3306
      name: mysql
      targetPort: 3306
      protocol: TCP
  clusterIP: None      
  selector: 
    name: mysql

---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    name: mysql  
spec:
  serviceName: "mysql"
  replicas: 3
  template:
    metadata:
      labels:
        name: mysql
    spec:
      containers:
      - name: mysql
        image: severalnines/mariadb:10.1
        ports:
        - containerPort: 3306
          name: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-pass
                key: password
          - name: DISCOVERY_SERVICE
            value: etcd:2379
          - name: XTRABACKUP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-pass
                key: password
          - name: CLUSTER_NAME
            value: percona
          - name: MYSQL_DATABASE
            value: mydatabase
          - name: MYSQL_USER
            value: myuser
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysqluser-pass
                key: password
        readinessProbe:
          exec:
            command:
            - /healthcheck.sh
            - --readiness
          initialDelaySeconds: 120
          periodSeconds: 1
        livenessProbe:
          exec:
            command:
            - /healthcheck.sh
            - --liveness
          initialDelaySeconds: 120
          periodSeconds: 1
        volumeMounts:
        - name: db
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: db
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
